---
title: ''
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plots without goodwill/grievance

```{r}
#Nation p
#a=0.1 #mutual fear,
#b=0.7 #expenditure
#r=0 #goodwill/grievance

#Nation g
#c=0.2 #mutual fear
#d=0.1 #expenditure
#s=0 #goodwill/grievance

#Simulation variables
t = 50
dt=0.1
steps=t/dt

euler = function(a,b,c,d,r,s) {
  #Matrix and initial
  ArmsRace = matrix(0,nrow=3,ncol=steps+1) #3 rows are for t,p,g, n+1 columns for including both endpoints of time (start at 0)
  ArmsRace[1,1]=0
  ArmsRace[2,1]=0.5 #p initial condition
  ArmsRace[3,1]=1 #g initial condition


#Euler Method
for (i in 1:steps) {
  t_i=ArmsRace[1,i]
  p_i=ArmsRace[2,i]
  g_i=ArmsRace[3,i]
  
  dp=a*g_i-b*p_i+r
  dg=c*p_i-d*g_i+s
  
  ArmsRace[1,i+1]=t_i+dt
  ArmsRace[2,i+1]=p_i+dt*dp
  ArmsRace[3,i+1]=g_i+dt*dg
}
  return(ArmsRace)
}

#bd>ac
ArmsRace = euler(a=0.1,b=0.7,c=0.2,d=0.1,r=0,s=0)
png("bdgeac.png", width=1000, height=1000) # Saves plot as a png
par(cex=3.5)
plot(ArmsRace[1,], ArmsRace[2,], type = "l",col="blue",
xlab="Time", ylab="National Arms",
main ="a=0.1, b=0.7, c=0.2, d=0.1",
ylim=range(c(ArmsRace[2,],ArmsRace[3,])), lwd=10)
lines(ArmsRace[1,],ArmsRace[3,],col="red",lwd=10)
legend("topright",legend=c("Nation P","Nation G"),col=c("blue","red"),lwd=10)
dev.off()

##bd<ac
ArmsRace = euler(0.5,0.5,0.2,0.1,0,0)
png("bdleac.png", width=1000, height=1000)
par(cex=3.5)
plot(ArmsRace[1,], ArmsRace[2,], type = "l",col="blue",
xlab="Time", ylab="National Arms",
main ="a=0.5, b=0.5, c=0.2, d=0.1",
ylim=range(c(ArmsRace[2,],ArmsRace[3,])), lwd=10)
lines(ArmsRace[1,],ArmsRace[3,],col="red",lwd=10)
legend("topleft",legend=c("Nation P","Nation G"),col=c("blue","red"),lwd=10)
dev.off()

##EDGE CASE: bd=ac
ArmsRace = euler(0.7,0.5,0.5,0.7,0,0)
png("bdeqac.png", width=1000, height=1000)
par(cex=3.5)
plot(ArmsRace[1,], ArmsRace[2,], type = "l",col="blue",
xlab="Time", ylab="National Arms",
main ="a=0.7, b=0.5, c=0.5, d=0.7",
ylim=range(c(ArmsRace[2,],ArmsRace[3,])), lwd=10)
lines(ArmsRace[1,],ArmsRace[3,],col="red",lwd=10)
legend("right",legend=c("Nation P","Nation G"),col=c("blue","red"),lwd=10)
dev.off()
```

# Plots with goodwill/grievances

```{r}
# Use the euler function to look at each case depending on varying r,s values. 
# Maybe create an updated euler function to cap the spending values when they turn negative
```

# Plots with mutual logistic fear

```{r}
# Create a new euler function with the logistic adjustments and fit the plots. 
```


